use utoipa::OpenApi;

use crate::{
    api,
    api::{
        AuthStatus, ConnectionInput, ConnectionView, Credentials, DatetimePreviewRequest,
        DatetimePreviewResponse, OkResponse, PasswordChange, ProbeCapabilities, ProbeRequest,
        ProbeResponse, ResolvedSetting, SettingValue, TokenCreate, TokenCreated, TokenSummary,
        UserSummary,
    },
    connector::{
        BrowsePage, BrowseParent, BrowseRequest, CellValue, ConnectorSchema, DisplayRow,
        ExpansionPolicy, FieldSpec, FieldTransform, FieldType, FilterSpec, FilterType, FilterValue,
        LabelRow, MaterializeRequest, RelationshipSpec, ResourceSpec, RowRef, RowValue, Tier, View,
    },
    models::{
        BatchRequest, BatchRowError, BatchSummary, Color, Dimension, ErrorBody, ErrorResponse,
        Extent, Fit, Flow, FlowDirection, FlowOverflow, FontSize, HealthResponse, HorizontalAlign,
        InputControl, InputSpec, LabelInput, Layout, LayoutItem, Options, Overflow,
        ParamDefaultError, ParamDefaultReport, ParamSpec, ParamType, ParamValue, Placement, Point,
        Position, PrintRequest, QrParams, ReloadResponse, RenameGroupRequest, RenameGroupResponse,
        RenderLabelRequest, Shape, SheetPosition, Size, SizeValue, Stroke, TemplateDetail,
        TemplateFormat, TemplateGroupUpdate, TemplateInputs, TemplateInputsRequest,
        TemplateInputsResponse, TemplateList, TemplateSummary, VariableValue, VerticalAlign,
    },
    store::Printer,
};

#[derive(OpenApi)]
#[openapi(
    paths(
        api::health,
        api::list_templates,
        api::list_groups,
        api::delete_group,
        api::update_template_group_name,
        api::reload_templates,
        api::get_template,
        api::template_source,
        api::thumbnail,
        api::template_inputs,
        api::put_template,
        api::update_template_group,
        api::delete_template,
        api::list_printers,
        api::create_printer,
        api::get_printer,
        api::replace_printer,
        api::delete_printer,
        api::set_printer_default,
        api::clear_printer_default,
        api::probe_printer,
        api::get_variables,
        api::put_variable,
        api::get_settings,
        api::put_setting,
        api::delete_setting,
        api::preview_datetime_format,
        api::render_label,
        api::batch,
        api::print_label,
        api::import_csv,
        api::list_favorites,
        api::add_favorite,
        api::remove_favorite,
        api::recent_templates,
        api::setup,
        api::login,
        api::logout,
        api::me,
        api::change_password,
        api::list_users,
        api::create_user_h,
        api::delete_user_h,
        api::list_tokens,
        api::create_token_h,
        api::delete_token_h,
        api::list_connections,
        api::create_connection,
        api::get_connection_h,
        api::update_connection_h,
        api::delete_connection_h,
        api::connection_schema,
        api::connection_browse,
        api::connection_materialize
    ),
    servers((url = "/api")),
    components(
        schemas(
            HealthResponse,
            VariableValue,
            ResolvedSetting,
            SettingValue,
            DatetimePreviewRequest,
            DatetimePreviewResponse,
            ReloadResponse,
            Printer,
            ProbeRequest,
            ProbeResponse,
            ProbeCapabilities,
            TemplateList,
            TemplateSummary,
            TemplateFormat,
            TemplateDetail,
            TemplateGroupUpdate,
            TemplateInputs,
            InputSpec,
            InputControl,
            TemplateInputsRequest,
            TemplateInputsResponse,
            RenameGroupRequest,
            RenameGroupResponse,
            Options,
            ParamDefaultError,
            ParamDefaultReport,
            ParamSpec,
            ParamType,
            ParamValue,
            LayoutItem,
            Layout,
            Color,
            Stroke,
            Flow,
            FlowDirection,
            FlowOverflow,
            Point,
            Position,
            Placement,
            Extent,
            SheetPosition,
            Dimension,
            Size,
            SizeValue,
            Overflow,
            Shape,
            FontSize,
            Fit,
            QrParams,
            HorizontalAlign,
            VerticalAlign,
            RenderLabelRequest,
            BatchRequest,
            PrintRequest,
            BatchSummary,
            BatchRowError,
            LabelInput,
            ErrorResponse,
            ErrorBody,
            Credentials,
            PasswordChange,
            TokenCreate,
            AuthStatus,
            UserSummary,
            TokenSummary,
            TokenCreated,
            OkResponse,
            ConnectionInput,
            ConnectionView,
            FieldTransform,
            ConnectorSchema,
            ResourceSpec,
            FieldSpec,
            FilterSpec,
            RelationshipSpec,
            View,
            FieldType,
            FilterType,
            Tier,
            RowRef,
            CellValue,
            DisplayRow,
            BrowseRequest,
            BrowseParent,
            BrowsePage,
            FilterValue,
            MaterializeRequest,
            ExpansionPolicy,
            RowValue,
            LabelRow
        )
    ),
    tags(
        (name = "labeler", description = "Label rendering service"),
        (name = "auth", description = "Authentication, users, and API tokens"),
        (name = "settings", description = "Typed application configuration"),
        (name = "favorites", description = "Per-user favorites and recent templates")
    )
)]
pub struct ApiDoc;
