use utoipa::OpenApi;

use crate::{
    api,
    api::{
        AuthStatus, ConnectionCreate, ConnectionUpdate, ConnectionView, Credentials,
        DatetimePreviewRequest, DatetimePreviewResponse, OkResponse, PasswordChange,
        ProbeCapabilities, ProbeResponse, ResolvedSetting, SettingValue, TokenCreate, TokenCreated,
        TokenSummary, UserSummary,
    },
    connector::{
        BrowsePage, BrowseParent, BrowseRequest, CellValue, ConnectorSchema, DisplayRow,
        ExpansionPolicy, FieldSpec, FieldType, FilterSpec, FilterType, FilterValue, LabelRow,
        MaterializeRequest, RelationshipSpec, ResourceSpec, RowRef, RowValue, Tier, View,
    },
    models::{
        BatchRowError, BatchSummary, ErrorBody, ErrorResponse, HealthResponse, LabelInput,
        NewPrinter, ParamControl, ParamEntry, ParamSpec, ParamType, ParamValue, PrintRequest,
        Printer, PrinterConnection, PrinterUpdate, ReloadResponse, RenderLabelRequest,
        RenderProfile, RenderRequest, SheetPosition, TemplateDetail, TemplateFormat, TemplateList,
        TemplateSummary, VariableValue,
    },
};

#[derive(OpenApi)]
#[openapi(
    paths(
        api::health,
        api::list_templates,
        api::reload_templates,
        api::get_template,
        api::template_source,
        api::thumbnail,
        api::create_template,
        api::replace_template,
        api::delete_template,
        api::list_printers,
        api::create_printer,
        api::get_printer,
        api::replace_printer,
        api::delete_printer,
        api::probe_printer,
        api::get_variables,
        api::put_variable,
        api::get_settings,
        api::put_setting,
        api::delete_setting,
        api::preview_datetime_format,
        api::render_label,
        api::render_labels,
        api::print_labels,
        api::list_favorites,
        api::add_favorite,
        api::remove_favorite,
        api::recent_templates,
        api::setup,
        api::login,
        api::logout,
        api::me,
        api::change_password,
        api::list_users,
        api::create_user_h,
        api::delete_user_h,
        api::list_tokens,
        api::create_token_h,
        api::delete_token_h,
        api::list_connections,
        api::create_connection,
        api::get_connection_h,
        api::update_connection_h,
        api::delete_connection_h,
        api::connection_schema,
        api::connection_browse,
        api::connection_materialize
    ),
    servers((url = "/api")),
    components(
        schemas(
            HealthResponse,
            VariableValue,
            ResolvedSetting,
            SettingValue,
            DatetimePreviewRequest,
            DatetimePreviewResponse,
            ReloadResponse,
            Printer,
            NewPrinter,
            PrinterUpdate,
            PrinterConnection,
            RenderProfile,
            ProbeResponse,
            ProbeCapabilities,
            TemplateList,
            TemplateSummary,
            TemplateFormat,
            TemplateDetail,
            ParamControl,
            ParamEntry,
            ParamSpec,
            ParamType,
            ParamValue,
            SheetPosition,
            RenderLabelRequest,
            RenderRequest,
            PrintRequest,
            BatchSummary,
            BatchRowError,
            LabelInput,
            ErrorResponse,
            ErrorBody,
            Credentials,
            PasswordChange,
            TokenCreate,
            AuthStatus,
            UserSummary,
            TokenSummary,
            TokenCreated,
            OkResponse,
            ConnectionCreate,
            ConnectionUpdate,
            ConnectionView,
            ConnectorSchema,
            ResourceSpec,
            FieldSpec,
            FilterSpec,
            RelationshipSpec,
            View,
            FieldType,
            FilterType,
            Tier,
            RowRef,
            CellValue,
            DisplayRow,
            BrowseRequest,
            BrowseParent,
            BrowsePage,
            FilterValue,
            MaterializeRequest,
            ExpansionPolicy,
            RowValue,
            LabelRow
        )
    ),
    tags(
        (name = "labeler", description = "Label rendering service"),
        (name = "auth", description = "Authentication, users, and API tokens"),
        (name = "settings", description = "Typed application configuration"),
        (name = "favorites", description = "Per-user favorites and recent templates")
    )
)]
pub struct ApiDoc;
