use utoipa::OpenApi;

use crate::{
    api,
    api::{
        AuthStatus, ConnectionInput, Credentials, DatetimePreviewRequest, DatetimePreviewResponse,
        OkResponse, PasswordChange, ResolvedSetting, SettingValue, TokenCreate, TokenCreated,
        TokenSummary, UserSummary,
    },
    connector::{
        BrowsePage, BrowseParent, BrowseRequest, CellValue, ConnectorSchema, DisplayRow,
        ExpansionPolicy, FieldSpec, FieldType, FilterSpec, FilterType, LabelRow,
        MaterializeRequest, RelationshipSpec, ResourceSpec, RowRef, Tier, View,
    },
    models::{
        AutoSize, BatchRequest, BatchRowError, BatchSummary, Dimension, ErrorBody, ErrorResponse,
        Fit, FontSize, HealthResponse, HorizontalAlign, LabelInput, Layout, LayoutItem, Options,
        Placement, Point, Position, QrParams, ReloadResponse, RenderLabelRequest, SheetPosition,
        Size, SizeValue, TemplateDetail, TemplateFormat, TemplateList, TemplateSummary,
        VariableValue, VerticalAlign,
    },
    store::Printer,
};

#[derive(OpenApi)]
#[openapi(
    paths(
        api::health,
        api::list_templates,
        api::create_template,
        api::reload_templates,
        api::get_template,
        api::template_source,
        api::thumbnail,
        api::replace_template,
        api::delete_template,
        api::list_printers,
        api::create_printer,
        api::get_printer,
        api::replace_printer,
        api::delete_printer,
        api::get_variables,
        api::put_variable,
        api::get_settings,
        api::put_setting,
        api::delete_setting,
        api::preview_datetime_format,
        api::render_label,
        api::batch,
        api::import_csv,
        api::setup,
        api::login,
        api::logout,
        api::me,
        api::change_password,
        api::list_users,
        api::create_user_h,
        api::delete_user_h,
        api::list_tokens,
        api::create_token_h,
        api::delete_token_h,
        api::list_connections,
        api::create_connection,
        api::get_connection_h,
        api::update_connection_h,
        api::delete_connection_h,
        api::connection_schema,
        api::connection_browse,
        api::connection_materialize
    ),
    servers((url = "/api")),
    components(
        schemas(
            HealthResponse,
            VariableValue,
            ResolvedSetting,
            SettingValue,
            DatetimePreviewRequest,
            DatetimePreviewResponse,
            ReloadResponse,
            Printer,
            TemplateList,
            TemplateSummary,
            TemplateFormat,
            TemplateDetail,
            Options,
            LayoutItem,
            Layout,
            Point,
            Position,
            Placement,
            SheetPosition,
            Dimension,
            Size,
            SizeValue,
            AutoSize,
            FontSize,
            Fit,
            QrParams,
            HorizontalAlign,
            VerticalAlign,
            RenderLabelRequest,
            BatchRequest,
            BatchSummary,
            BatchRowError,
            LabelInput,
            ErrorResponse,
            ErrorBody,
            Credentials,
            PasswordChange,
            TokenCreate,
            AuthStatus,
            UserSummary,
            TokenSummary,
            TokenCreated,
            OkResponse,
            ConnectionInput,
            ConnectorSchema,
            ResourceSpec,
            FieldSpec,
            FilterSpec,
            RelationshipSpec,
            View,
            FieldType,
            FilterType,
            Tier,
            RowRef,
            CellValue,
            DisplayRow,
            BrowseRequest,
            BrowseParent,
            BrowsePage,
            MaterializeRequest,
            ExpansionPolicy,
            LabelRow
        )
    ),
    tags(
        (name = "labeler", description = "Label rendering service"),
        (name = "auth", description = "Authentication, users, and API tokens"),
        (name = "settings", description = "Typed application configuration")
    )
)]
pub struct ApiDoc;
